### ISSUE TITLE
Check page tree integrity throw exception under TYPO3 12

### ISSUE THREAD

**Issue by mediaessenz** [lolli42/dbdoctor#113]
If I start the command with `ddev typo3 dbdoctor:health -m interactive` I get this exception in the console:
```
Check page tree integrity
-------------------------

 Class: PagesBrokenTree
 Actions: remove
 This health check finds "pages" records with their "pid" set to pages that do
 not exist in the database. Pages without proper connection to the tree root are never
 shown in the backend. They are removed.

Uncaught TYPO3 Exception PDOStatement::bindParam(): Argument #4 ($maxLength) must be of type int, null given
thrown in file /var/www/html/vendor/typo3/cms-core/Classes/Database/Driver/DriverStatement.php
in line 104
```

Tried it with TYPO3 12.4.11 and 12.4.12 under PHP 8.2.16

**Comment by mediaessenz** [comment]
I was able to find the pain point:
It's this call inside the RecordsHelper::getRecord method of your extension, which produces the exception:
```php
$statement->bindParam(1, $uid, Connection::PARAM_INT);
```
As far as I see, this `bindParam` method of the doctrine AbstractStatementMiddleware is deprecated (see https://github.com/doctrine/dbal/pull/5563) and bindValue should be used instead.

**Comment by mediaessenz** [comment]
Maybe the problem came from the choosen database driver, which is 'pdo_mysql' in my case.

**Comment by mediaessenz** [comment]
Replacing all `bindParam` calls in this RecordsHelper class with `bindValue` solve the problem.

**Comment by lolli42** [comment]
tag 0.6.2
