### ISSUE TITLE
See if dbdoctor covers existing mess_detector checks

### ISSUE THREAD

**Issue by lolli42** [lolli42/dbdoctor#17]
https://github.com/macopedia/mess_detector

@tmotyl pinged us on this extension. Looks as if dbdoctor performs at least partially very similar checks already. We could have a look at what may be missing and could be added.

**Comment by tmotyl** [comment]
I've also put some ideas into issues, so it might be useful to check them too:
https://github.com/macopedia/mess_detector/issues

**Comment by lolli42** [comment]
- [ ]  t3origuid:checkt3origuidequalsuid

**Comment by lolli42** [comment]
Closing: Main checks implemented, others should have new issues in dbdoctor if really needed.
