### ISSUE TITLE
Ensure localized record uniqueness

### ISSUE THREAD

**Issue by lolli42** [lolli42/dbdoctor#9]
Look for "more than one localization of a default language record exists for one specific language".
Some of our instances suffer from this: For whatever reason there are two or more localizations of a l10n_parent record.
Backend and Frontend then behave funny: When deleting such a localization, the other one pops up "below" instead. When copying a page with such a scenario, DataHandler creates even more funny state and it's worse in combination with workspaces.
Challenge: Get this check right even with workspace being involved. It's also not trivial to decide which record to keep, that needs investigation, the pid of the affected records (pid is fixed by an existing check already) and their sorting probably influence this.

**Comment by josefglatz** [comment]
## Cheatsheet for testing and brainstorming how to handling such records

```sql
SELECT uid, pid, sys_language_uid, l10n_source, slug, title, hidden, cruser_id, COUNT(uid) 
FROM pages
WHERE l10n_source != 0
GROUP BY l10n_source, sys_language_uid
HAVING COUNT(uid) > 1;
```

```sql
SELECT uid, pid, sys_language_uid, l10n_source, slug, title, hidden FROM `pages`
WHERE uid = 53 OR l10n_source = 53
ORDER BY sys_language_uid;
```

**Comment by lolli42** [comment]
no result yet, but some candidates with this sql (note not ws-aware):

```
SELECT uid, pid, deleted, sys_language_uid, l18n_parent, t3ver_wsid, t3ver_state, header
FROM tt_content
WHERE deleted=0 
AND l18n_parent IN (SELECT l18n_parent FROM tt_content WHERE deleted=0 AND l18n_parent != 0 GROUP BY l18n_parent, sys_language_uid HAVING COUNT(uid) > 1) ORDER BY pid;
```
